export { default as Home } from './Home'
export { default as Main } from './Main'
export { default as AllProducts } from './AllProducts'
export { default as Filter } from './Filter'
export { default as Detail } from './Detail'
export { default as Compare } from './Compare'
export { default as Favourites } from './Favourites'
export { default as SignUp } from './SignUp'
export {default as ControlPanel } from './ControlPanel'