export { default as Home } from './Home'
export { default as Main } from './Main'
export { default as AllProducts } from './AllProducts'
export { default as Filter } from './Filter'
export { default as Detail } from './Detail'